#
# Better Go Playground Docker image deployment workflow
#
# Builds and deploys image to Docker hub when a new release created.
# Uses DOCKER_USER, DOCKER_PASS and GTAG env vars from GitHub repo secrets.
#
# see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: Deploy To Docker Hub
on:
  release:
    types:
      - created
  repository_dispatch:
    types: manual-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/v}
      - name: Build Docker image
        run: |
          make docker-image TAG=${{ env.RELEASE_VERSION }} GTAG=${{ secrets.GTAG }}
      - name: Deploy image to Docker hub
        run: |
          make docker-push-image TAG=${{ env.RELEASE_VERSION }} \
            DOCKER_USER=${{ secrets.DOCKER_USER }} \
            DOCKER_PASS=${{ secrets.DOCKER_PASS }}
